### ISSUE TITLE
Cygwin does not show prompts to overwrite already existing files

### ISSUE THREAD

**Issue by Raane** [NordicSemiconductor/pc-nrfutil#33]
In the event that a file already exists, an nrfutil operation which would overwrite the file will pause and query the user before doing so "File found at filename. Do you want to overwrite the file?  [y/N]". In Cygwin nrfutil will still pause, but the message is not displayed. To the user it seems nrfutil has crashed.

To reproduce this issue, open a cygwin and execute the following commands:

```
nrfutil keys generate private.pem
nrfutil keys generate private.pem
```

**Comment by carlescufi** [comment]
This is really not an nrfutil issue, but a Cygwin one as far as I can tell. The way Cygwin handles the terminal is slightly different than standard cmd.exe, and that is probably what is causing the text not to be displayed, since we use standard Python functionality to output the prompts (based on click)
